### ISSUE TITLE
Revision Required

### ISSUE THREAD

**Issue by keyuyan1145** [Blaine-Reid/django_todo#1]
Hey! I'm not done looking over it yet, but so far, I've noticed two things:

1. Is it necessary to have a Tag and TodoTag? You could achieve the foreign key constraint by adding an attribute for the Task model?
2. Did you get to implement the Comment model?

Let me know if you have any questions.

**Comment by Blaine-Reid** [comment]
I was following along with my book "web development with django" to do a
many to many and it showed setting it up in that manner. Have the Tag and
the ToDoTag as an intermediary table. They did a book review but same
concept.

And yes I used the comment
